[package]
name = "rust_learn"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
log = "0.4.21"
fs4 = "0.8.2"
async-std = "1.13.2"
async-trait = "0.1.89"
tokio = { version = "1.49.0", features = ["full"] }